services:
  - type: background
    name: zookeeper
    env: docker
    dockerImage: bitnami/zookeeper:latest
    envVars:
      - key: ALLOW_ANONYMOUS_LOGIN
        value: "yes"
    plan: free

  - type: background
    name: kafka
    env: docker
    dockerImage: bitnami/kafka:latest
    envVars:
      - key: KAFKA_BROKER_ID
        value: "1"
      - key: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_LISTENERS
        value: "PLAINTEXT://:9092"
      - key: KAFKA_ADVERTISED_LISTENERS
        value: "PLAINTEXT://kafka:9092"
      - key: ALLOW_ANONYMOUS_LOGIN
        value: "yes"
    plan: free
    dependsOn:
      - zookeeper
